---
title: 'Getting Unstuck: Ch 2 & 3, What it means to be Unstuck'
author: Chris Umphlett
date: '2019-02-10'
slug: getting-unstuck-ch-2-3
categories: []
tags:
  - book
description: ''
externalLink: ''
---

I am reading Matt Perman's *How to Get Unstuck* and taking on the writing exercise at the end of each chapter. [More information in this article on the introduction](https://chrisumphlett.github.io/posts/perman-unstuck-1/). 

Chapters 2 and 3 describe what being unstuck looks like. 

## Chapter 2
Perman defines being unstuck as 
> Getting important work done through obstacles, and to keep doing it over and over again.

If you are unstuck you will be using these skills: Clarity, Discipline, Focus, Energy, Speed, Estimation, Completion and Love for others.

### Exercise: How are you doing at obeying the command to be "abounding in the work of the Lord"? Are there things you are not doing that you should start doing, or things you are doing that you should stop doing?

> Adequately...? There are things I feel very confidently that I should be doing, that I am doing. Then there are a bunch of other things across my different roles that tend to come and go in and out of my attention and prioritization. There are more things I would like to do, and that I feel are important, than I can do. I need to spend more time thinking, dreaming, praying, and discussing what others about these options to gain greater clarity.

## Chapter 3
Perman articulates his vision for "The Unstuck Cycle," where those who are unstuck help others who are stuck. He argues that we tend to err by assuming that others lack the will to change, rather than the skill. Skill can be taught and our approach to helping others who are stuck should be done without the pre-judgment that it is because of their lack of focus or desire.

### Exercise: Who in your life is stuck right now? What can you do to help them get unstuck?

> The first person who came to my mind was my wife because she has made several comments to me lately that sounded like someone who was stuck. I gave her an overview of these first few chapters and she agreed, particularly on the 3 days a week where she is at home with our children. Those days she feels torn between spending time with them and getting other things done. We had a good conversation that I expect we will come back to about ways she can increase the skills Perman mentioned in chapter 2 as well as how I can support and help her.

