---
title: Dynamic resume's built in R with the vitae package
author: Chris Umphlett
date: '2019-03-06'
slug: vitae-package
categories: []
tags:
  - R
description: ''
externalLink: ''
---

*Updated Sept 25, 2019*

A couple of months ago I came across the `vitae` package which was recently developed by Mitchell O'Hara Wild. I have been using the same basic resume template for over 10 years, mainly by default, but I really liked the layout offered by one of the `vitae` templates and the ability to build it with R Markdown turned a chore into something fun to do (keeping the resume current).

The package can be installed from CRAN with `install.packages('vitae')`. The templates originally set up were more geared towards academics with Curriculum Vitae's (the template I am using, "awesomecv", even had the words "Curriculum Vitae" hardcoded in the footer). I have added some features to make the package more resume-friendly at the developer's [Github repo](https://github.com/ropenscilabs/vitae). *Update*: These changes have now been integrated into the production version at CRAN.

**In order to change the footer so that it does not say Curriculum Vitae, you must utilize the `docname` parameter in the yaml header.**

Check out [my resume](/files/Umphlett_resume_current.pdf) as an example of the updated "awesomecv" template, and the [R Markdown code that creates it](/files/vitae_resume_chrisumphlett.Rmd).

What I particularly like is the top section which allows you to better define yourself and draw others attention to your portfolio/website/etc. I also took the opportunity when I switched to this format to put Skills first as I believe that in the field of data science skills are as important as experience, particularly soft skills which I didn't draw attention to previously when I just listed software or languages at the bottom of the resume. 